remote_theme: pmarsceill/just-the-docs

title: Mackey Makey

google_analytics: UA-131578130-2

aux_links:
    "Voir la source sur GitHub":
      - "//github.com/serresebastien/Makey-Makey"
      
exclude: ["LICENSE.txt", "README.md"]
